### ISSUE TITLE
Testes unitários

### ISSUE THREAD

**Issue by jrsilva95** [teaching-labs/avaliacao-3-jrsilva95-leuhx#3]
Adicionar testes unitários no sistema

**Comment by jrsilva95** [comment]
Adicionado os testes de segurança no PR #13

**Comment by leuhx** [comment]
Adicionados testes de Administrador e Estudantes PR #14

**Comment by jrsilva95** [comment]
Adicionados teste unitário  Respostas Dashboard no PR #15
